language: android

android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-27.0.3                # Build tools version
    - android-27                        # Target SDK version
    - extra-android-m2repository        # Support repo
    - extra-google-m2repository         # Google repo

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager --licenses

script:
  - ./gradlew build

branches:
  only:
    - master
    - dev

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle